export type { IPlayerType, IPlayer, IHUMAN, IAI } from './player.interface'
export type { IMatchState } from './match-state.interface'
export type { ITurn } from './turn.interface'
export type { ILobby } from './lobby.interface'
export type { IQueue } from './queue.interface'
export type { IMatch } from './match.interface'
export type { IMatchService } from './match-service.interface'
export type { IObserver, ISubject } from './observable.interface'
export type { IPlayersStore, UUID } from './players-store.interface'
export type { IServer } from './server.interface'

export { PlayerType } from './player.interface'
