# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# File for Pull Request on main branch
name: PR on main

# When a PR is opened to main
on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [14.x]

    # Define Steps
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Make sure we have all branches
    - name: Fetch other branches
      run: git fetch --no-tags --prune --depth=5 origin master
    
    - name: Install environment
      run: yarn install

    - name: Run lint
      run: yarn run affected:lint -- --base="origin/main"
      
    - name: Tests coverage
      run: yarn run affected:test -- --base="origin/main" --codeCoverage
